Draft: Handles authenticated access to Kafka
strmprivacy/data-plane-helm-chart pull request #19
Opened 2022-06-28 13:03 UTC by bvdeenen

2022-06-29 11:36 UTC, trietsch requested changes

2022-06-29 11:36 UTC, trietsch commented on README.md
> +# Running with SASL/PLAIN+TLS Kafka cluster
Move this up, as a section under the installation instructions.

2022-06-29 11:36 UTC, trietsch commented on helm/resources/event-gateway/application.conf
> +    eventProducer {
All this configuration should be optional based on whether or not there actually is Kafka Auth configured.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/_helpers.tpl
> +            # from template installationEnvironmentVariables
Unnecessary comment

2022-06-29 11:36 UTC, trietsch commented on helm/templates/_helpers.tpl
> +            # from template selfHostedEnvironmentVariables
Unnecessary comment

2022-06-29 11:36 UTC, trietsch commented on helm/templates/_helpers.tpl
> +            {{ if .Values.kafkaSecurityConfig.enabled }}
The `if` statement should move to the places where this `kafkaSecurityEnvironmentVars` is included.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/_helpers.tpl
> +  "kafka.user": {{ .user | default "" | b64enc | quote }}
Default empty strings? If someone configures Kafka Auth, we should enforce them to have a non-empty username and password.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/_helpers.tpl
> +            {{ if .component.configuration.kafkaAuth.password }}
The environment variables should only be set if both properties in the Kafka Auth block are set.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/batch-exporters-agent/deployment.yaml
> +{{ $image := include "image" $data }}
Can this line be merged with the definition of `$data`? That way you don't need an awkward name like as generic as `data` because you need to name it.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/batch-exporters-agent/config-secret.yaml
> +{{ if $component.enabled }}
The if statement regarding whether or not the Kafka Auth is required should actually determine whether this secret is required.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/batch-exporters-agent/deployment.yaml
> +          {{ include "kafkaSecurityEnvironmentVars" .}}
The if statement regarding whether or not the Kafka Auth is required should determine whether or not to include these vars.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/common/image-pull-secret.yaml
> +  .dockerconfigjson: >-
Why did this line change? This is very sensitive for errors....

2022-06-29 11:36 UTC, trietsch commented on helm/templates/esr-proxy/config-secret.yaml
> +{{ if $component.enabled }}
The if statement regarding whether or not the Kafka Auth is required should actually determine whether this secret is required.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/esr-proxy/deployment.yaml
> +          {{- template "client-truststore-volume-mount" . }}
The if statement regarding whether or not the Kafka Auth is required should actually determine whether this volume mount is required.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/event-gateway/config-secret.yaml
> +{{ if $component.enabled }}
The if statement regarding whether or not the Kafka Auth is required should actually determine whether this secret is required.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/event-gateway/deployment.yaml
> +            {{ include "kafkaSecurityEnvironmentVars" .}}
The if statement regarding whether or not the Kafka Auth is required should determine whether or not to include these vars.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/event-gateway/deployment.yaml
> +          volumeMounts:
The if statement regarding whether or not the Kafka Auth is required should determine whether or not to include these vars.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/streams-agent/config-secret.yaml
> +{{ if $component.enabled }}
The if statement regarding whether or not the Kafka Auth is required should actually determine whether this secret is required.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/streams-agent/deployment.yaml
> +            {{ include "kafkaSecurityEnvironmentVars" .}}
The if statement regarding whether or not the Kafka Auth is required should determine whether or not to include these vars.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/streams-agent/deployment.yaml
> +          {{ if .Values.kafkaSecurityConfig.enabled }}
Yes, this is what I mean. Please also do the check like this everywhere in the Helm chart.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/streams-agent/deployment.yaml
> +      volumes:
However, the volume should also be optional, based on whether or not the Kafka Auth is enabled.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/web-socket/config-secret.yaml
> +{{ if $component.enabled }}
The if statement regarding whether or not the Kafka Auth is required should actually determine whether this secret is required.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/web-socket/deployment.yaml
> +            {{ include "kafkaSecurityEnvironmentVars" .}}
The if statement regarding whether or not the Kafka Auth is required should determine whether or not to include these vars.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/web-socket/deployment.yaml
> +          volumeMounts:
The if statement regarding whether or not the Kafka Auth is required should actually determine whether this volume mount is required.

2022-06-29 11:36 UTC, trietsch commented on helm/templates/web-socket/deployment.yaml
> +        {{- template "client-truststore-volume" . }}
The if statement regarding whether or not the Kafka Auth is required should actually determine whether this volume is required.

2022-06-29 11:36 UTC, trietsch commented on helm/values.yaml
> +kafkaSecurityConfig:
Please create a generic `configuration` or `sharedConfiguration` section under which we can list various things, such as bootstrapservers as well. I propose:
```
configuration:
  kafka:
    bootstrapServers:
    securityConfig:
      enabled: false
      securityProtocol: "PLAINTEXT"
      sslTruststoreSecretName: "banana"
```

2022-06-29 11:36 UTC, trietsch commented on kafka-tls-client.yaml
> +kind: Deployment
Shouldn't this be a `Pod`? More like a one time thing and not something that stays alive and eats up resources?

2022-06-29 11:40 UTC, bvdeenen commented on helm/templates/_helpers.tpl
> +            # from template installationEnvironmentVariables
But useful for debugging the kubernetes manifest

2022-06-29 11:40 UTC, bvdeenen commented on helm/templates/_helpers.tpl
> +            {{ if .Values.kafkaSecurityConfig.enabled }}
That is significantly more code duplication. I tend to disagree.

2022-06-29 11:42 UTC, bvdeenen commented on kafka-tls-client.yaml
> +kind: Deployment
Could be, yes. But the pod will stay alive until you delete it, and the deployment also. Makes no difference in resources.

2022-06-29 11:42 UTC, trietsch commented on helm/templates/_helpers.tpl
> +            {{ if .Values.kafkaSecurityConfig.enabled }}
But it does lead to **correct** Kubernetes manifests, whereas your current solution produces manifests that are incorrect, as they include parts that are not necessary.

2022-06-29 11:43 UTC, trietsch commented on kafka-tls-client.yaml
> +kind: Deployment
Or until the pod finishes its work. In contrast to a deployment. Therefore, I'd propose a Pod with a finite amount of work.

2022-06-29 11:44 UTC, trietsch commented on helm/templates/_helpers.tpl
> +            # from template installationEnvironmentVariables
Fair enough, feel free to leave these in place.

2022-06-29 11:45 UTC, bvdeenen commented on helm/values.yaml
> +kafkaSecurityConfig:
At the  moment, bootstrapServers is inside the `kafka` section, and is taken from the enabled Kafka chart if you don't explicitly set it (see `helm/values.yaml kafka` in the master branch). Moving this attribute into a separate section does not make it clearer.

2022-06-29 11:47 UTC, trietsch commented on helm/values.yaml
> +kafkaSecurityConfig:
We should support other bootstrapservers, that's why I was thinking of a generic section of shared configuration among the different apps.

2022-06-29 12:13 UTC, bvdeenen commented on kafka-tls-client.yaml
> +kind: Deployment
The pod is started in order to be able to `exec bash` into it. This means the pod stays alive  until explicitly deleted.

2022-06-29 12:52 UTC, bvdeenen commented on helm/templates/_helpers.tpl
> +            {{ if .Values.kafkaSecurityConfig.enabled }}
I don't see your point. The resulting k8s manifest is identical, it's only the statement of the {{ if }} that is changed.

2022-06-29 12:52 UTC, bvdeenen commented on README.md
> +# Running with SASL/PLAIN+TLS Kafka cluster
Agree

2022-07-01 12:11 UTC, trietsch commented on helm/templates/batch-exporters-agent/deployment.yaml
> +{{ $image := include "image" $data }}
Try to use regular parentheses

2022-07-01 12:11 UTC, trietsch commented on kafka-tls-client.yaml
> +kind: Deployment
Create a separate dir in the repo, like `test-utils`, and copy the raw URL as an `ExternalCodeBlock` in the docs.

2022-07-01 12:13 UTC, trietsch commented on helm/values.yaml
> +kafkaSecurityConfig:
We're leaving this as it is for now. Later.

2022-07-01 12:38 UTC, bvdeenen commented on helm/resources/event-gateway/application.conf
> +    eventProducer {
Fixed in commit bfc139c703ef

2022-07-01 12:40 UTC, bvdeenen commented on kafka-tls-client.yaml
> +kind: Deployment
Done in 7583bd8

2022-07-01 13:14 UTC, bvdeenen commented on helm/templates/event-gateway/deployment.yaml
> +            - mountPath: /home/nonroot/application.conf
yes it is always present. Its value in the PLAINTEXT configuration is this:
```
app {
    kafka {
        eventProducer {
            kafkaSecurityConfig {
                securityProtocol = "PLAINTEXT"
            }
        }
        encryptionKeysProducer {
            kafkaSecurityConfig {
                securityProtocol = "PLAINTEXT"
            }
        }
        usageProducer {
            kafkaSecurityConfig {
                securityProtocol = "PLAINTEXT"
            }
        }
    }
}
```

2022-07-01 13:58 UTC, trietsch approved these changes

2022-07-01 14:05 UTC, merged