Feature/strm 2034
strmprivacy/data-plane-helm-chart pull request #28
Opened 2022-11-23 15:40 UTC by bobvandenhoogen

2022-12-02 12:57 UTC, trietsch requested changes

2022-12-02 12:57 UTC, trietsch commented on helm/templates/_helpers.tpl
> +    {{- if ne .values.registry.url "europe-west4-docker.pkg.dev" }}
Here the same predicate with the check on the installation type being `SELF_HOSTED` also needs to be added.

2022-12-02 12:57 UTC, trietsch commented on helm/templates/_helpers.tpl
> +    {{- printf "%s/%s:%s" .values.registry.url (.component.image.name | replace "/" "_") .component.image.version | quote -}}
Make sure that we document the expected location for the images. Now this replace is quite implicit (same applies for the mirror STRM images script in our docs)

2022-12-02 14:02 UTC, trietsch requested changes

2022-12-07 12:48 UTC, bvdeenen approved these changes

2023-01-31 09:57 UTC, merged

2023-01-31 09:58 UTC, strmprivacy-io commented
:tada: This PR is included in version 1.21.0 :tada:

The release is available on [GitHub release](https://github.com/strmprivacy/data-plane-helm-chart/releases/tag/v1.21.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: